"""initial schema

Revision ID: 6df40f000d9b
Revises: 
Create Date: 2026-08-22 15:55:10.609544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6df40f000d9b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('external_customer_id', sa.String(length=64), nullable=False),
    sa.Column('segment', sa.Enum('NEW', 'STANDARD', 'HIGH_VALUE', name='customersegment'), nullable=False),
    sa.Column('opted_out', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_external_customer_id'), 'customers', ['external_customer_id'], unique=True)
    op.create_table('evaluation_results',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('dataset_split', sa.String(length=16), nullable=False),
    sa.Column('metrics_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evaluation_results_run_id'), 'evaluation_results', ['run_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('razorpay_payment_id', sa.String(length=64), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('payment_method', sa.Enum('CARD', 'UPI', 'NETBANKING', 'WALLET', 'EMI', name='paymentmethod'), nullable=False),
    sa.Column('status', sa.Enum('CREATED', 'FAILED', 'RECOVERED', 'UNRECOVERABLE', 'PENDING', name='paymentstatus'), nullable=False),
    sa.Column('source', sa.Enum('WEBHOOK', 'CSV', 'SIMULATOR', name='eventsource'), nullable=False),
    sa.Column('dataset_split', sa.Enum('TRAIN', 'HOLDOUT', name='datasetsplit'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_customer_id'), 'payments', ['customer_id'], unique=False)
    op.create_index('ix_payments_customer_status', 'payments', ['customer_id', 'status'], unique=False)
    op.create_index(op.f('ix_payments_razorpay_payment_id'), 'payments', ['razorpay_payment_id'], unique=False)
    op.create_index(op.f('ix_payments_status'), 'payments', ['status'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.String(length=64), nullable=False),
    sa.Column('payment_id', sa.Uuid(), nullable=False),
    sa.Column('stage', sa.String(length=32), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('system_version', sa.String(length=32), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_event_id'), 'audit_logs', ['event_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_payment_id'), 'audit_logs', ['payment_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_index('ix_audit_payment_timestamp', 'audit_logs', ['payment_id', 'timestamp'], unique=False)
    op.create_table('payment_attempts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('payment_id', sa.Uuid(), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('failure_code', sa.String(length=64), nullable=True),
    sa.Column('failure_reason', sa.String(length=256), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw_event_json', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_attempts_payment_number', 'payment_attempts', ['payment_id', 'attempt_number'], unique=False)
    op.create_index(op.f('ix_payment_attempts_payment_id'), 'payment_attempts', ['payment_id'], unique=False)
    op.create_table('recovery_cases',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('payment_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'RECOVERED', 'STOPPED', 'ESCALATED', 'CLOSED_UNRECOVERED', name='recoverycasestatus'), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('revenue_at_risk', sa.Integer(), nullable=False),
    sa.Column('recovery_attempts', sa.Integer(), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recovery_cases_payment_id'), 'recovery_cases', ['payment_id'], unique=False)
    op.create_index(op.f('ix_recovery_cases_status'), 'recovery_cases', ['status'], unique=False)
    op.create_table('ai_analyses',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('recovery_case_id', sa.Uuid(), nullable=False),
    sa.Column('stage', sa.Enum('DIAGNOSIS', 'ACTION_PROPOSAL', name='aistage'), nullable=False),
    sa.Column('model_provider', sa.String(length=32), nullable=False),
    sa.Column('raw_output_json', sa.JSON(), nullable=False),
    sa.Column('diagnosis', sa.String(length=64), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('reasoning_summary', sa.String(length=512), nullable=False),
    sa.Column('schema_valid', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['recovery_case_id'], ['recovery_cases.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_analyses_recovery_case_id'), 'ai_analyses', ['recovery_case_id'], unique=False)
    op.create_table('recovery_actions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('recovery_case_id', sa.Uuid(), nullable=False),
    sa.Column('proposed_action', sa.Enum('RETRY_PAYMENT', 'SEND_REMINDER', 'OFFER_ALTERNATE_METHOD', 'SCHEDULE_RETRY', 'ESCALATE_HUMAN', 'STOP', name='recoveryactiontype'), nullable=False),
    sa.Column('policy_allowed', sa.Boolean(), nullable=False),
    sa.Column('policy_reason', sa.String(length=256), nullable=False),
    sa.Column('executed', sa.Boolean(), nullable=False),
    sa.Column('execution_result', sa.String(length=16), nullable=True),
    sa.Column('revenue_recovered', sa.Integer(), nullable=False),
    sa.Column('human_override', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['recovery_case_id'], ['recovery_cases.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recovery_actions_recovery_case_id'), 'recovery_actions', ['recovery_case_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recovery_actions_recovery_case_id'), table_name='recovery_actions')
    op.drop_table('recovery_actions')
    op.drop_index(op.f('ix_ai_analyses_recovery_case_id'), table_name='ai_analyses')
    op.drop_table('ai_analyses')
    op.drop_index(op.f('ix_recovery_cases_status'), table_name='recovery_cases')
    op.drop_index(op.f('ix_recovery_cases_payment_id'), table_name='recovery_cases')
    op.drop_table('recovery_cases')
    op.drop_index(op.f('ix_payment_attempts_payment_id'), table_name='payment_attempts')
    op.drop_index('ix_attempts_payment_number', table_name='payment_attempts')
    op.drop_table('payment_attempts')
    op.drop_index('ix_audit_payment_timestamp', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_payment_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_event_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_payments_status'), table_name='payments')
    op.drop_index(op.f('ix_payments_razorpay_payment_id'), table_name='payments')
    op.drop_index('ix_payments_customer_status', table_name='payments')
    op.drop_index(op.f('ix_payments_customer_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_evaluation_results_run_id'), table_name='evaluation_results')
    op.drop_table('evaluation_results')
    op.drop_index(op.f('ix_customers_external_customer_id'), table_name='customers')
    op.drop_table('customers')
    # ### end Alembic commands ###
